//! The named glyph sets and the whole list, apart from the enum so `mod.rs` stays short: the
//! gallery draws `ALL`, and the icon tests lock each set to its source.

use super::Icon;

impl Icon {
    /// The mailo set, in the order of the keys of `ICON`.
    ///
    /// The icon tests lock this list to `icons.js`.
    pub const MAILO: &[Icon] = &[
        Icon::Inbox,
        Icon::Star,
        Icon::Archive,
        Icon::Clock,
        Icon::Trash,
        Icon::Mail,
        Icon::MailOpen,
        Icon::Tag,
        Icon::Refresh,
        Icon::Send,
        Icon::Command,
        Icon::Columns,
        Icon::Group,
        Icon::Panel,
        Icon::Square,
        Icon::Maximize,
        Icon::Corner,
        Icon::Undo,
        Icon::Check,
        Icon::X,
        Icon::Paperclip,
        Icon::Pen,
        Icon::Key,
        Icon::FilePen,
        Icon::OctagonAlert,
        Icon::Pin,
        Icon::Reply,
        Icon::ReplyAll,
        Icon::Forward,
        Icon::Search,
        Icon::Settings,
        Icon::PanelLeft,
        Icon::Plus,
    ];

    /// The shell set, in design/08-ICONS.md section 1.6's order, then the control center's own
    /// `Switches` (sill FINDINGS Q103).
    pub const SHELL: &[Icon] = &[
        Icon::Wifi,
        Icon::WifiLow,
        Icon::WifiHigh,
        Icon::WifiOff,
        Icon::Ethernet,
        Icon::Battery,
        Icon::BatteryLow,
        Icon::BatteryMedium,
        Icon::BatteryFull,
        Icon::BatteryCharging,
        Icon::BatteryWarning,
        Icon::Bluetooth,
        Icon::BluetoothConnected,
        Icon::BluetoothOff,
        Icon::Volume,
        Icon::Volume1,
        Icon::Volume2,
        Icon::VolumeX,
        Icon::Mic,
        Icon::MicOff,
        Icon::Sun,
        Icon::Moon,
        Icon::SunMoon,
        Icon::Power,
        Icon::Lock,
        Icon::Bell,
        Icon::BellOff,
        Icon::Grid,
        Icon::Window,
        Icon::Monitor,
        Icon::Keyboard,
        Icon::ChevronLeft,
        Icon::ChevronRight,
        Icon::ChevronUp,
        Icon::ChevronDown,
        Icon::Folder,
        Icon::File,
        Icon::Image,
        Icon::Terminal,
        Icon::StickyNote,
        Icon::Camera,
        Icon::Download,
        Icon::Upload,
        Icon::Copy,
        Icon::Link,
        Icon::Sparkles,
        Icon::Gauge,
        Icon::Brightness,
        Icon::Switches,
    ];

    /// Glyphs for a consumer's actions beyond the two sets (Lucide, `geometry_actions`).
    pub const ACTIONS: &[Icon] = &[
        Icon::Printer,
        Icon::FolderInput,
        // mailo gaps 6.
        Icon::Ellipsis,
        Icon::EllipsisVertical,
        // Lock and switcher parts (M11).
        Icon::ArrowRight,
        Icon::CapsLock,
    ];

    /// The control center's, the power menu's and Now Playing's glyphs (Lucide,
    /// `geometry_control`; sill FINDINGS Q81). `Power` is in the shell set.
    pub const CONTROL: &[Icon] = &[
        Icon::Play,
        Icon::Pause,
        Icon::SkipBack,
        Icon::SkipForward,
        Icon::LogOut,
        Icon::Restart,
        Icon::Headphones,
        Icon::Speaker,
        Icon::Mouse,
        Icon::Gamepad,
        Icon::Phone,
    ];

    /// Every glyph: the mailo set, the shell set, the actions, then the control set.
    pub const ALL: &[Icon] = &[
        Icon::Inbox,
        Icon::Star,
        Icon::Archive,
        Icon::Clock,
        Icon::Trash,
        Icon::Mail,
        Icon::MailOpen,
        Icon::Tag,
        Icon::Refresh,
        Icon::Send,
        Icon::Command,
        Icon::Columns,
        Icon::Group,
        Icon::Panel,
        Icon::Square,
        Icon::Maximize,
        Icon::Corner,
        Icon::Undo,
        Icon::Check,
        Icon::X,
        Icon::Paperclip,
        Icon::Pen,
        Icon::Key,
        Icon::FilePen,
        Icon::OctagonAlert,
        Icon::Pin,
        Icon::Reply,
        Icon::ReplyAll,
        Icon::Forward,
        Icon::Search,
        Icon::Settings,
        Icon::PanelLeft,
        Icon::Plus,
        Icon::Wifi,
        Icon::WifiLow,
        Icon::WifiHigh,
        Icon::WifiOff,
        Icon::Ethernet,
        Icon::Battery,
        Icon::BatteryLow,
        Icon::BatteryMedium,
        Icon::BatteryFull,
        Icon::BatteryCharging,
        Icon::BatteryWarning,
        Icon::Bluetooth,
        Icon::BluetoothConnected,
        Icon::BluetoothOff,
        Icon::Volume,
        Icon::Volume1,
        Icon::Volume2,
        Icon::VolumeX,
        Icon::Mic,
        Icon::MicOff,
        Icon::Sun,
        Icon::Moon,
        Icon::SunMoon,
        Icon::Power,
        Icon::Lock,
        Icon::Bell,
        Icon::BellOff,
        Icon::Grid,
        Icon::Window,
        Icon::Monitor,
        Icon::Keyboard,
        Icon::ChevronLeft,
        Icon::ChevronRight,
        Icon::ChevronUp,
        Icon::ChevronDown,
        Icon::Folder,
        Icon::File,
        Icon::Image,
        Icon::Terminal,
        Icon::StickyNote,
        Icon::Camera,
        Icon::Download,
        Icon::Upload,
        Icon::Copy,
        Icon::Link,
        Icon::Sparkles,
        Icon::Gauge,
        Icon::Brightness,
        Icon::Switches,
        Icon::Printer,
        Icon::FolderInput,
        // mailo gaps 6.
        Icon::Ellipsis,
        Icon::EllipsisVertical,
        Icon::ArrowRight,
        Icon::CapsLock,
        Icon::Play,
        Icon::Pause,
        Icon::SkipBack,
        Icon::SkipForward,
        Icon::LogOut,
        Icon::Restart,
        Icon::Headphones,
        Icon::Speaker,
        Icon::Mouse,
        Icon::Gamepad,
        Icon::Phone,
    ];
}
