//! Motion: every animation as data, the settle timers that replace `animationend`, and the
//! state machines that decide what moves (design/05-MOTION.md, design/06-INTERACTIONS.md).

pub mod anim;
pub(crate) mod css;
pub mod detail;
#[cfg(feature = "dioxus")]
pub mod drag;
#[cfg(feature = "dioxus")]
pub mod drag_return;
#[cfg(feature = "dioxus")]
pub mod entrance;
pub mod hover_intent;
pub mod kit;
#[cfg(feature = "dioxus")]
pub mod machine;
pub mod pane_slide;
pub mod presence;
pub mod projection;
#[cfg(feature = "dioxus")]
pub(crate) mod pulse;
pub mod pulse_key;
pub mod recipe;
pub(crate) mod recipe_detail;
pub(crate) mod recipe_own;
pub(crate) mod reduced;
pub mod roster;
pub mod rubber;
pub mod settle;
pub mod spring;
#[cfg(feature = "dioxus")]
pub mod spring_point;
pub mod spring_spec;
pub mod swipe;
pub mod timeline;
#[cfg(feature = "dioxus")]
pub mod timer;
#[cfg(feature = "dioxus")]
pub mod use_collapse;
#[cfg(feature = "dioxus")]
pub mod use_roster;
#[cfg(feature = "dioxus")]
pub mod use_spring;
#[cfg(feature = "dioxus")]
pub mod use_swipe;
pub mod velocity;
pub mod wake;
