//! The faces, shipped inside the binary as bytes (design/02-TYPE.md section 2): Inter and Inter
//! Display (the System typeface), Bricolage Grotesque, Karla and Space Mono (the Editorial
//! typeface; Space Mono is also the code face in both), and Noto Serif.
//!
//! On Blitz the bytes are registered with the renderer's font context once (`ds-native`'s
//! `register_fonts`); nothing about fonts is in the stylesheet. The `webview-fonts` feature
//! keeps mailo's interim path, `@font-face` rules with base64 `data:` URIs generated by
//! `build.rs`, for a consumer still on the webview.
//!
//! The files are subset TTFs (latin and latin-ext, Google Fonts' own split), made from mailo's
//! WOFF2 copies by `scripts/subset-fonts.sh`, because fontique reads sfnt and not WOFF2
//! (FINDINGS F14). The script also names every face's family the way `--font-*` asks for it.
//! Space Mono's latin files are the exception: they are subset from the Space Mono 1.003 release
//! with the latin file's own code points plus U+2190-2193, because Google's latin range keeps
//! `↑` and `↓` but drops `←` and `→`, and a Small key cap's fallback arrows read as dashes
//! (FINDINGS "Sheet and modal parts", sill Q95). Every other glyph is the same outline.
//! Inter is cut from the official Inter 4.1 release by `scripts/cut-inter.sh` (version and
//! SHA-256 recorded there): its variable font pinned to `opsz` 14 for Inter (400-700, italic
//! 400) and to `opsz` 32 for Inter Display (500-800), since the renderer sets no optical size.
//! Licences are in `assets/fonts/OFL-*.txt`.

use crate::tokens::Family;

/// Upright or italic.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum FaceStyle {
    /// Roman.
    Normal,
    /// Italic.
    Italic,
}

/// The weights a face covers: one for a static instance, a range for a variable face.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct Weight {
    /// The lightest weight.
    pub min: u16,
    /// The heaviest weight.
    pub max: u16,
}

/// Which unicode subset a file carries.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Subset {
    /// Basic Latin and Latin-1, general punctuation.
    Latin,
    /// Latin Extended.
    LatinExt,
}

/// One font file.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct Face {
    /// The family name it registers as, the name a `--font-*` stack leads with: `"Inter"`.
    pub name: &'static str,
    /// The job it was cut for (under the typeface that names it; Space Mono also does
    /// [`Family::Code`] in both).
    pub family: Family,
    /// Upright or italic.
    pub style: FaceStyle,
    /// The weights it covers.
    pub weight: Weight,
    /// The subset it carries.
    pub subset: Subset,
    /// The file.
    pub bytes: &'static [u8],
}

macro_rules! face {
    ($name:literal, $family:expr, $style:expr, $min:expr, $max:expr, $subset:expr, $file:literal) => {
        Face {
            name: $name,
            family: $family,
            style: $style,
            weight: Weight {
                min: $min,
                max: $max,
            },
            subset: $subset,
            bytes: include_bytes!(concat!("../assets/fonts/", $file)),
        }
    };
}

/// Every face the design system ships.
pub static FACES: &[Face] = &[
    face!(
        "Inter",
        Family::Ui,
        FaceStyle::Normal,
        400,
        700,
        Subset::Latin,
        "inter-normal-400-700-latin.ttf"
    ),
    face!(
        "Inter",
        Family::Ui,
        FaceStyle::Normal,
        400,
        700,
        Subset::LatinExt,
        "inter-normal-400-700-latin-ext.ttf"
    ),
    face!(
        "Inter",
        Family::Ui,
        FaceStyle::Italic,
        400,
        400,
        Subset::Latin,
        "inter-italic-400-latin.ttf"
    ),
    face!(
        "Inter",
        Family::Ui,
        FaceStyle::Italic,
        400,
        400,
        Subset::LatinExt,
        "inter-italic-400-latin-ext.ttf"
    ),
    face!(
        "Inter Display",
        Family::Display,
        FaceStyle::Normal,
        500,
        800,
        Subset::Latin,
        "inter-display-normal-500-800-latin.ttf"
    ),
    face!(
        "Inter Display",
        Family::Display,
        FaceStyle::Normal,
        500,
        800,
        Subset::LatinExt,
        "inter-display-normal-500-800-latin-ext.ttf"
    ),
    face!(
        "Bricolage Grotesque",
        Family::Display,
        FaceStyle::Normal,
        500,
        800,
        Subset::Latin,
        "bricolage-grotesque-normal-500-800-latin.ttf"
    ),
    face!(
        "Bricolage Grotesque",
        Family::Display,
        FaceStyle::Normal,
        500,
        800,
        Subset::LatinExt,
        "bricolage-grotesque-normal-500-800-latin-ext.ttf"
    ),
    face!(
        "Karla",
        Family::Ui,
        FaceStyle::Normal,
        400,
        700,
        Subset::Latin,
        "karla-normal-400-700-latin.ttf"
    ),
    face!(
        "Karla",
        Family::Ui,
        FaceStyle::Normal,
        400,
        700,
        Subset::LatinExt,
        "karla-normal-400-700-latin-ext.ttf"
    ),
    face!(
        "Karla",
        Family::Ui,
        FaceStyle::Italic,
        400,
        400,
        Subset::Latin,
        "karla-italic-400-latin.ttf"
    ),
    face!(
        "Karla",
        Family::Ui,
        FaceStyle::Italic,
        400,
        400,
        Subset::LatinExt,
        "karla-italic-400-latin-ext.ttf"
    ),
    face!(
        "Space Mono",
        Family::Data,
        FaceStyle::Normal,
        400,
        400,
        Subset::Latin,
        "space-mono-normal-400-latin.ttf"
    ),
    face!(
        "Space Mono",
        Family::Data,
        FaceStyle::Normal,
        400,
        400,
        Subset::LatinExt,
        "space-mono-normal-400-latin-ext.ttf"
    ),
    face!(
        "Space Mono",
        Family::Data,
        FaceStyle::Normal,
        700,
        700,
        Subset::Latin,
        "space-mono-normal-700-latin.ttf"
    ),
    face!(
        "Space Mono",
        Family::Data,
        FaceStyle::Normal,
        700,
        700,
        Subset::LatinExt,
        "space-mono-normal-700-latin-ext.ttf"
    ),
    face!(
        "Noto Serif",
        Family::Serif,
        FaceStyle::Normal,
        400,
        700,
        Subset::Latin,
        "noto-serif-normal-400-700-latin.ttf"
    ),
    face!(
        "Noto Serif",
        Family::Serif,
        FaceStyle::Normal,
        400,
        700,
        Subset::LatinExt,
        "noto-serif-normal-400-700-latin-ext.ttf"
    ),
    face!(
        "Noto Serif",
        Family::Serif,
        FaceStyle::Italic,
        400,
        700,
        Subset::Latin,
        "noto-serif-italic-400-700-latin.ttf"
    ),
    face!(
        "Noto Serif",
        Family::Serif,
        FaceStyle::Italic,
        400,
        700,
        Subset::LatinExt,
        "noto-serif-italic-400-700-latin-ext.ttf"
    ),
];

/// `@font-face` rules with the faces as base64 `data:` URIs, for a consumer still on the
/// webview. Generated by `build.rs`.
#[cfg(feature = "webview-fonts")]
pub fn font_face_css() -> &'static str {
    include_str!(concat!(env!("OUT_DIR"), "/fonts.css"))
}

#[cfg(test)]
mod tests {
    use super::{FACES, FaceStyle, Subset};
    use crate::appearance::Typeface;
    use crate::tokens::Family;

    #[test]
    fn every_family_ships_both_subsets() {
        // Each (name, style, weight) appears once per subset, and no file is empty.
        for face in FACES {
            assert!(!face.bytes.is_empty(), "{face:?} is empty");
            let twins = FACES
                .iter()
                .filter(|other| {
                    other.name == face.name
                        && other.style == face.style
                        && other.weight == face.weight
                })
                .map(|other| other.subset)
                .collect::<Vec<_>>();
            assert_eq!(
                twins.len(),
                2,
                "{} {:?} {:?}",
                face.name,
                face.style,
                face.weight
            );
            assert!(twins.contains(&Subset::Latin) && twins.contains(&Subset::LatinExt));
        }
        // Every stack, in either typeface, leads with a face that ships upright.
        for typeface in Typeface::ALL {
            for family in Family::ALL {
                let name = family.face_name(typeface);
                assert!(
                    FACES
                        .iter()
                        .any(|face| face.name == name && face.style == FaceStyle::Normal),
                    "{family:?} under {typeface:?} leads with {name}, which ships no upright face"
                );
            }
        }
    }

    #[test]
    fn every_face_is_a_font() {
        // An sfnt a font context can register: TrueType outlines (0x00010000) or CFF (`OTTO`).
        // A WOFF2 (`wOF2`) would be skipped by fontique; see FINDINGS F14.
        const SFNT: [&[u8]; 2] = [&[0, 1, 0, 0], b"OTTO"];
        for face in FACES {
            let magic = face.bytes.get(..4).unwrap_or_default();
            assert!(
                SFNT.contains(&magic),
                "{} {:?} {:?} starts {magic:02x?}",
                face.name,
                face.style,
                face.subset
            );
        }
    }
}
