//! The accent band: every accent, built-in or lent by a Space, generated by one function from a
//! hue inside bounds (design/03-COLOR.md section 20, settled: B, Airy, 2026-09-27).
//!
//! A band fixes, per scheme, where the solid fill sits in OKLCH lightness, how much chroma any
//! accent may carry, which ink goes on the fill, where the text accent starts, and how strongly
//! the translucent wash and the focus ring show. [`accent_roles`] turns a hue (and a weight, for
//! a Space's quiet echo) into the roles a component paints: the solid fill, the ink on it, the
//! text accent, the wash (the fill at an alpha over whatever is beneath) and the focus ring (the
//! text accent at an alpha). Every step it takes moves a colour toward passing a gate in
//! [`floors`], the way mailo's Space accent steps its lightness (section 4.3); the sweep test
//! proves every 5 degrees of hue, every weight step and both schemes clear them.
//!
//! The accent table (`tokens::accent_table::accent_of`) and the Space accent
//! (`space::palette::derive`) both call [`accent_roles`] with [`BAND`]; there is no other
//! derivation of an accent colour.

pub(crate) mod band;
pub(crate) mod derive;
pub mod floors;
pub(crate) mod grounds;
pub(crate) mod legibility;
pub(crate) mod oklab;
pub(crate) mod picked;
pub(crate) mod roles;
pub(crate) mod text_grounds;
pub(crate) mod widget_grounds;

pub use band::{AccentBand, AccentPick, ChromaSpan, Hue, InkRule, Milli, SchemeBand, Weight};
pub use derive::accent_roles;
pub use grounds::{card_grounds, card_ink, over};
pub use legibility::{Legibility, legibility};
pub use oklab::distance;
pub use picked::{BAND, hue_of};
pub use roles::AccentRoles;
pub use text_grounds::{
    BACKDROPS, Ground, GroundKind, TEXT_MATERIALS, TextOn, least_on, material_grounds,
    text_grounds, text_on,
};
pub use widget_grounds::{WALLPAPERS, widget_grounds};

#[cfg(test)]
mod tests;
