//! The accent band: every accent, built-in or lent by a Space, generated by one function from a
//! hue inside bounds (design/03-COLOR.md section 20, **proposed, awaiting the user's pick**).
//!
//! A band fixes, per scheme, where the solid fill sits in OKLCH lightness, how much chroma any
//! accent may carry, which ink goes on the fill, where the text accent starts, and how strongly
//! the translucent wash and the focus ring show. [`accent_roles`] turns a hue (and a weight, for
//! a Space's quiet echo) into the roles a component paints: the solid fill, the ink on it, the
//! text accent, the wash (the fill at an alpha over whatever is beneath) and the focus ring (the
//! text accent at an alpha). Every step it takes moves a colour toward passing a gate in
//! [`floors`], the way mailo's Space accent steps its lightness (section 4.3); the sweep test
//! proves every 5 degrees of hue, every weight step and both schemes clear them.
//!
//! Nothing paints from this yet: the default accent is still the accent table's Postmark quad.
//! The gallery's `--accent-sheet` renders the candidate bands beside it for the user's pick.

mod band;
mod candidates;
mod derive;
pub mod floors;
mod grounds;
mod legibility;
mod roles;

pub use band::{AccentBand, AccentPick, ChromaSpan, Hue, InkRule, Milli, SchemeBand, Weight};
pub use candidates::{Candidate, hue_of};
pub use derive::accent_roles;
pub use grounds::{card_grounds, card_ink, over};
pub use legibility::{Legibility, legibility};
pub use roles::AccentRoles;

#[cfg(test)]
mod tests;
