//! With the `webview-fonts` feature, turns the vendored fonts into `@font-face` rules for a
//! consumer still on the webview. Moved from mailo's `mail-app/build.rs`.
//!
//! The faces ship inside the binary as `data:` URIs. Three other routes were rejected:
//! - a network font makes the window phone a font host on every launch, the same leak as a
//!   remote image;
//! - a custom protocol handler is a path-shaped lookup;
//! - `asset!` pulls in manganis.
//!
//! `concat!` can include a file but cannot base64-encode one, so the encoding happens here.
//! It writes `$OUT_DIR/fonts.css`, which `fonts::font_face_css` includes. The encoder is
//! fifteen lines, so it is not worth a build dependency.
//!
//! Without the feature nothing is generated: on Blitz the bytes in `fonts::FACES` are
//! registered with the renderer instead.
//!
//! The files are Google Fonts' own `latin` and `latin-ext` subsets, with Google's
//! `unicode-range`s. Licences are in `assets/fonts/OFL-*.txt`.

use std::env;
use std::fs;
use std::path::PathBuf;

const LATIN: &str = "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, \
    U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, \
    U+FFFD";
const LATIN_EXT: &str = "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, \
    U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, \
    U+2113, U+2C60-2C7F, U+A720-A7FF";

/// Family, style, weight (a range for a variable face), and the file stem before the subset.
const FACES: &[(&str, &str, &str, &str)] = &[
    (
        "Bricolage Grotesque",
        "normal",
        "500 800",
        "bricolage-grotesque-normal-500-800",
    ),
    ("Karla", "normal", "400 700", "karla-normal-400-700"),
    ("Karla", "italic", "400", "karla-italic-400"),
    ("Space Mono", "normal", "400", "space-mono-normal-400"),
    ("Space Mono", "normal", "700", "space-mono-normal-700"),
];

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    if env::var_os("CARGO_FEATURE_WEBVIEW_FONTS").is_none() {
        return;
    }
    let dir =
        PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap_or_default()).join("assets/fonts");
    println!("cargo:rerun-if-changed={}", dir.display());
    let mut css = String::from("/* Generated by build.rs from assets/fonts. Do not edit. */\n");
    for (family, style, weight, stem) in FACES {
        for (subset, range) in [("latin-ext", LATIN_EXT), ("latin", LATIN)] {
            let path = dir.join(format!("{stem}-{subset}.woff2"));
            println!("cargo:rerun-if-changed={}", path.display());
            let bytes = match fs::read(&path) {
                Ok(bytes) => bytes,
                Err(why) => panic!("font {}: {why}", path.display()),
            };
            css.push_str(&format!(
                "@font-face {{ font-family: \"{family}\"; font-style: {style}; font-weight: {weight}; \
                 font-display: block; src: url(data:font/woff2;base64,{}) format(\"woff2\"); \
                 unicode-range: {range}; }}\n",
                base64(&bytes)
            ));
        }
    }
    let out = PathBuf::from(env::var_os("OUT_DIR").unwrap_or_default()).join("fonts.css");
    if let Err(why) = fs::write(&out, css) {
        panic!("writing {}: {why}", out.display());
    }
}

/// Standard base64 with padding, RFC 4648 section 4.
fn base64(bytes: &[u8]) -> String {
    const ALPHABET: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = String::with_capacity(bytes.len().div_ceil(3) * 4);
    for chunk in bytes.chunks(3) {
        let n = chunk
            .iter()
            .enumerate()
            .fold(0u32, |n, (i, b)| n | u32::from(*b) << (16 - 8 * i));
        for i in 0..4 {
            if i <= chunk.len() {
                out.push(char::from(ALPHABET[(n >> (18 - 6 * i) & 63) as usize]));
            } else {
                out.push('=');
            }
        }
    }
    out
}
