#!/usr/bin/env bash
# The canonical fork [patch] block (vello, anyrender, dioxus), published as docs/fork-patches.toml.
#   fork-patches.sh print                     the block, to paste into a consumer's workspace root
#   fork-patches.sh check <Cargo.toml>        exit 1 unless that manifest's [patch.crates-io]
#                                             carries exactly the block's entries
#   fork-patches.sh generate                  rewrite docs/fork-patches.toml from quire's root
#                                             Cargo.toml (the source of truth)
#   fork-patches.sh selftest                  the docs file matches the root; a changed copy fails
# Comments and blank lines are ignored when comparing; entries are compared as sorted lines.
set -euo pipefail
here=$(cd "$(dirname "$0")/.." && pwd)
block="$here/docs/fork-patches.toml"

# The [patch.crates-io] section of manifest $1, header included, up to the next table header.
section() {
  awk '/^\[/ { on = ($0 == "[patch.crates-io]") } on' "$1"
}

# Its entries only: no comments, no blank lines, sorted.
entries() {
  grep -vE '^[[:space:]]*(#|$)' | grep -v '^\[' | sort
}

check() {
  local manifest=$1 want have
  [ -f "$manifest" ] || { echo "fork-patches: no such file: $manifest" >&2; return 2; }
  want=$(entries <"$block")
  have=$(section "$manifest" | entries)
  if [ "$want" = "$have" ]; then
    echo "fork-patches: $manifest matches docs/fork-patches.toml"
    return 0
  fi
  echo "fork-patches: $manifest differs from docs/fork-patches.toml (< missing or changed, > extra):" >&2
  diff <(printf '%s\n' "$want") <(printf '%s\n' "$have") | grep -E '^[<>]' >&2 || true
  return 1
}

selftest() {
  local tmp
  tmp=$(mktemp -d)
  trap 'rm -rf "$tmp"' RETURN
  # The published block is quire's own.
  check "$here/Cargo.toml" >/dev/null
  # A consumer copy that moved a rev fails.
  sed '/^vello_common = /s/rev = "[0-9a-f]\{40\}"/rev = "0000000000000000000000000000000000000000"/' \
    "$here/Cargo.toml" >"$tmp/changed.toml"
  if check "$tmp/changed.toml" >/dev/null 2>&1; then
    echo "fork-patches selftest: a changed rev passed the check" >&2
    return 1
  fi
  # A copy that lost an entry fails.
  grep -v '^subsecond-types' "$here/Cargo.toml" >"$tmp/short.toml"
  if check "$tmp/short.toml" >/dev/null 2>&1; then
    echo "fork-patches selftest: a missing entry passed the check" >&2
    return 1
  fi
  # A manifest with no block fails.
  printf '[package]\nname = "x"\n' >"$tmp/none.toml"
  if check "$tmp/none.toml" >/dev/null 2>&1; then
    echo "fork-patches selftest: an empty manifest passed the check" >&2
    return 1
  fi
  echo "fork-patches selftest: ok"
}

case "${1:-}" in
  print) cat "$block" ;;
  check) check "${2:?usage: fork-patches.sh check <Cargo.toml>}" ;;
  generate)
    {
      echo "# Generated by scripts/fork-patches.sh generate from quire's root Cargo.toml. Paste into the"
      echo "# workspace root of every consumer that builds ds-blitz; \`fork-patches.sh check\` verifies a copy."
      section "$here/Cargo.toml"
    } >"$block" ;;
  selftest) selftest ;;
  *) echo "usage: fork-patches.sh print | check <Cargo.toml> | generate | selftest" >&2; exit 2 ;;
esac
