//! The card's colour tokens, light and dark (design/03-COLOR.md sections 3, 10-12).
//!
//! `color-mix()` is replaced by precomputed washes. The frame's `--f-*` are not here: they are
//! derived per Space ([`crate::FrameVars`]).
//!
//! Precomputed washes (section 11 and open decisions 3-4; every value here is proposed):
//! `--ok-wash` is `--ok` at .16 over transparent, exactly what `color-mix(in oklab, var(--ok)
//! 16%, transparent)` paints; `--warn-wash` is `--warn` 14% over `--surface`, mixed in OKLab
//! and rounded to 8 bits; `--danger-wash` takes the failing pill's form, `--danger` at .16 over
//! transparent (the spoof flag's 12% over `--raise` is within a step of it on white);
//! the accent family (`--accent`, `--accent-ink`, `--accent-soft`, `--accent-text`,
//! `--accent-ring`, `--seal`) is generated by the settled accent band (design/03-COLOR.md
//! section 20); each `data-accent` block writes all eight, and the value here is Blue's.

use super::accent_table::accent_of;
use super::hex::{Alpha, Colour, Hex};
use crate::appearance::{accent::Accent, theme::Scheme};
use crate::tokens::token::{CssValue, Token, TokenScope};
use ds_core::word::Word;

const fn solid(rgb: u32) -> Colour {
    Colour::Solid(rgb_hex(rgb))
}

const fn alpha(rgb: u32, thousandths: u16) -> Colour {
    Colour::Alpha(rgb_hex(rgb), Alpha(thousandths))
}

/// `0xRRGGBB` as a [`Hex`]; the shifts keep each byte.
const fn rgb_hex(rgb: u32) -> Hex {
    Hex([(rgb >> 16) as u8, (rgb >> 8) as u8, rgb as u8])
}

/// One card colour token.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Word, Token)]
#[token(prefix = "", kind = fixed, css = colour_css)]
pub enum ColourToken {
    /// `--paper`: page ground; inverse text on ink pills.
    Paper,
    /// `--surface`: card, list, rows.
    Surface,
    /// `--surface-2`: reader, composer, peek, mini, kbd.
    #[token(name = "surface-2")]
    Surface2,
    /// `--raise`: selected row, popovers, menus.
    Raise,
    /// `--ink`: primary text; inverse pill ground.
    Ink,
    /// `--ink-soft`: secondary text.
    InkSoft,
    /// `--ink-faint`: metadata.
    InkFaint,
    /// `--line`: borders and dividers.
    Line,
    /// `--line-soft`: inner dividers.
    LineSoft,
    /// `--accent`: the accent's solid fill (the primary button, the today disc, a toggle on).
    Accent,
    /// `--accent-ink`: text and glyphs on the fill.
    AccentInk,
    /// `--accent-soft`: the accent's translucent wash (a selected row, a menu highlight, a chip),
    /// the fill at an alpha over whatever lies beneath.
    AccentSoft,
    /// `--accent-text`: the accent as text or a thin mark on the card (a link, the month's title,
    /// a check, a caret, an unread dot, a selection border).
    AccentText,
    /// `--accent-text-material`: the same on a translucent material, where it must also read
    /// over a black or white backdrop; a Popover, Sheet or Toast root points `--accent-text` at
    /// it (design/03-COLOR.md section 20.6).
    AccentTextMaterial,
    /// `--seal`: defined, unused in the Spaces prototype (design/03-COLOR.md open decision 7).
    Seal,
    /// `--ok`: saved, live.
    Ok,
    /// `--warn`: star, dirty, attachment warning.
    Warn,
    /// `--danger`: spoof flag, lying link.
    Danger,
    /// `--scrim`: behind peek and the command menu.
    Scrim,
    /// `--foreign-ground`: the sender's page behind an original message.
    ForeignGround,
    /// `--ok-wash`: `--ok` at 16% over transparent.
    OkWash,
    /// `--warn-wash`: `--warn` at 14% over `--surface`.
    WarnWash,
    /// `--danger-wash`: `--danger` over transparent or `--raise` (open decision 3).
    DangerWash,
    /// `--accent-ring`: the text accent at the band's ring alpha (3:1 or better on every card
    /// ground): the keyboard focus ring and the destination ring.
    AccentRing,
    /// `--danger-ink`: text on `--danger` (the lying link pill's `#fff` in light, O-3; a dark
    /// ink in dark, where white on the lifted `--danger` measured 3.17:1).
    DangerInk,
    /// `--mark-ground`: the white chip under a provider mark (O-3).
    MarkGround,
    /// `--handle-ring`: the slider thumb's border (design/04-COMPONENTS.md section 5 and O-3;
    /// proposed: a quarter-strength ink ring in either scheme).
    HandleRing,
    /// `--on-hue`: the letter on a computed hue ground — the avatar's person and account
    /// tones (design/04-COMPONENTS.md O-3's `#fff`/`#FFFFFF` list, "fav text"; proposed:
    /// white in either scheme, since the hue itself is always mid-toned enough for it).
    OnHue,
    /// `--ok-ink`: text on `--ok` (a status pill), clearing 4.5:1 in either scheme.
    OkInk,
    /// `--warn-ink`: text on `--warn`, clearing 4.5:1 in either scheme.
    WarnInk,
    /// `--scrim-modal`: the dimming behind a modal that asks for a decision (a shutdown dialog),
    /// black at .40 in light and .55 in dark, where `--scrim` (.22) only pushes a peek back
    /// (sill FINDINGS "Sheet and modal parts"; design/03-COLOR.md section 17). A colour like
    /// `--scrim`, not an opacity, because its strength differs by scheme.
    ScrimModal,
    /// `--scroll-thumb`: the host's own overlay scrollbar thumb (design/11-BEHAVIOUR-scroll.md
    /// section 11.3.12): `--ink` at .5 alpha, over the layer's own .8 opacity (effective .4), in
    /// light; `--paper`'s equivalent (white at the same effective alpha) in dark.
    ScrollThumb,
    /// `--lock-ink`: the lock screen's type over the wallpaper, white in either scheme (the
    /// clock, the name, the field's dots; design/20-SURFACES.md section 1.9).
    LockInk,
    /// `--lock-ink-soft`: the lock screen's quieter line (the date, the hint, a placeholder),
    /// white at .78.
    LockInkSoft,
    /// `--lock-glass`: the lock screen's translucent field, flat white over the wallpaper (.24
    /// in light, .18 in dark); no blur is assumed (spike S15).
    LockGlass,
    /// `--lock-glass-strong`: the field's enter button and a hovered field, a step brighter.
    LockGlassStrong,
    /// `--lock-veil`: the dimming the lock screen lays over its wallpaper so white type reads on
    /// a pale picture (black at .12 in light, .28 in dark).
    LockVeil,
    /// `--spell-mark`: the dotted underline under a misspelt word in an `EditSurface`
    /// (design/04-COMPONENTS.md section 50; proposed): the danger hue at full strength, since
    /// a dot a few pixels across needs all of its chroma to read as red.
    SpellMark,
    /// `--scrim-idle`: the pre-screen-off idle overlay's colour, black, the same in both
    /// schemes — not `--scrim` or `--scrim-modal`, whose alphas are fixed. This one's opacity is
    /// the person's own `idle.dim_level_pct` (10..90), set inline by `IdleDim` itself
    /// (design/22-SETTINGS.md section 3.24; sill FINDINGS "sill idle": dim with an
    /// overlay, never real brightness), so the token carries no alpha of its own.
    ScrimIdle,
    /// `--knob-fill`: a switch's and a slider's knob, a plain white disc in either scheme (the
    /// reference's; design/29-SIZING.md section 4 rows 4 and 15), set off by its shadow.
    #[token(name = "knob-fill")]
    Knob,
    /// `--orb-bg`: the voice orb's ground, the ring it fades to at its rim and the dots over
    /// it (design/30 section 2.9). Values: the reference's oklch(95% .02 264.695)
    /// light, darkened to oklch(24% .02 264.695) in dark.
    OrbBg,
    /// `--orb-c1`: the orb's first glow, oklch(75% .15 350) (dark: 68%).
    OrbC1,
    /// `--orb-c2`: the orb's second glow, oklch(80% .12 200) (dark: 72%).
    OrbC2,
    /// `--orb-c3`: the orb's third glow, oklch(78% .14 280) (dark: 70%).
    OrbC3,
}

impl ColourToken {
    /// The value in `scheme`, with Blue as the accent (the band's roles,
    /// section 20).
    pub fn value(self, scheme: Scheme) -> Colour {
        // Only the accent family asks the band: the band measures against the card's grounds,
        // which are this table's too.
        let blue = || accent_of(Accent::Blue, scheme);
        let (light, dark) = match self {
            ColourToken::Accent | ColourToken::Seal => return Colour::Solid(blue().fill),
            ColourToken::AccentInk => return Colour::Solid(blue().ink),
            ColourToken::AccentSoft => return blue().wash_colour(),
            ColourToken::AccentText => return Colour::Solid(blue().text),
            ColourToken::AccentTextMaterial => return Colour::Solid(blue().text_material),
            ColourToken::AccentRing => return blue().ring_colour(),
            other => other.mac(),
        };
        match scheme {
            Scheme::Light => light,
            Scheme::Dark => dark,
        }
    }

    /// The Look (design/30-CATALOGUE.md section 3.2): the system window paper, white
    /// controls and content, and the label colours as solid greys. The label, secondary and
    /// tertiary levels sit at about 87, 64 and 48 % (dark: 91, 64 and 52 %), a little firmer than
    /// macOS's 85, 55 and 25 %, because the legibility gates (design/03-COLOR.md section 6)
    /// hold them to 4.5:1 over a blurred backdrop and the faint metadata to 3:1.
    fn mac(self) -> (Colour, Colour) {
        const WHITE: Colour = solid(0xFFFFFF);
        match self {
            ColourToken::Paper => (solid(0xECECEC), solid(0x1E1E1E)),
            ColourToken::Surface => (WHITE, solid(0x2A2A2A)),
            ColourToken::Surface2 => (solid(0xF5F5F5), solid(0x242424)),
            ColourToken::Raise => (WHITE, solid(0x323232)),
            ColourToken::Ink => (solid(0x202020), solid(0xE8E8E8)),
            ColourToken::InkSoft => (solid(0x5C5C5C), solid(0xA3A3A3)),
            ColourToken::InkFaint => (solid(0x858585), solid(0x858585)),
            ColourToken::Line => (solid(0xD9D9D9), solid(0x444444)),
            ColourToken::LineSoft => (solid(0xE6E6E6), solid(0x383838)),
            ColourToken::Ok => (solid(0x2C7A57), solid(0x5EB489)),
            ColourToken::Warn => (solid(0xA5761A), solid(0xD2A249)),
            ColourToken::Danger => (solid(0xB03A2A), solid(0xE0705A)),
            // The danger hue, as `--danger` (proposed, design/04-COMPONENTS.md section 50).
            ColourToken::SpellMark => (solid(0xB03A2A), solid(0xE0705A)),
            // Not redefined in dark (section 3).
            ColourToken::Scrim => (alpha(0x000000, 220), alpha(0x000000, 220)),
            // Opaque black in either scheme: `IdleDim` sets the overlay's own opacity from
            // `idle.dim_level_pct`, so the token itself carries no alpha (design/03-COLOR.md
            // section 17.3.3).
            ColourToken::ScrimIdle => (solid(0x000000), solid(0x000000)),
            ColourToken::Knob => (WHITE, WHITE),
            // The voice orb's four colours, the oklch values of the reference converted to
            // sRGB (`orb_colours_are_the_oklch_values_they_name` proves them); dark is the same
            // hues at a lower lightness so the glows do not dazzle on a dark ground.
            ColourToken::OrbBg => (solid(0xE8EFFC), solid(0x1B1F29)),
            ColourToken::OrbC1 => (solid(0xF383BB), solid(0xDF6AA6)),
            ColourToken::OrbC2 => (solid(0x43D5DC), solid(0x04BBC3)),
            ColourToken::OrbC3 => (solid(0xA9AFFE), solid(0x8D92F9)),
            // The sender's page stays white in a dark window (section 12).
            ColourToken::ForeignGround => (WHITE, WHITE),
            ColourToken::OkWash => (alpha(0x2C7A57, 160), alpha(0x5EB489, 160)),
            ColourToken::WarnWash => (solid(0xF2EBE1), solid(0x3F3930)),
            ColourToken::DangerWash => (alpha(0xB03A2A, 160), alpha(0xE0705A, 160)),
            // `#fff` on the lying link pill in light (`S:436`); in dark `--danger` is lifted to
            // `#E0705A`, where white measures 3.17:1, so the ink turns dark (mailo's `#1A0B08`,
            // 6.06:1). The legibility test gates every status pair in both schemes.
            ColourToken::DangerInk => (WHITE, solid(0x1A0B08)),
            // White on `--ok` in light (5.21:1); a dark green-black on the lifted dark `--ok`.
            ColourToken::OkInk => (WHITE, solid(0x0B1A12)),
            // White on light `--warn` is 4.03:1, under the gate, so both schemes take a dark ink.
            ColourToken::WarnInk => (solid(0x140D03), solid(0x140D03)),
            // A modal's dimming: stronger in dark, where the paper is already near black and the
            // sheet stands out by its hairline and shadow; the legibility test gates both.
            ColourToken::ScrimModal => (alpha(0x000000, 400), alpha(0x000000, 550)),
            // `--ink` at .5 over the layer's .8 opacity in light (effective .4); `--paper`'s
            // equivalent, white at the same effective alpha, in dark (design/11-BEHAVIOUR-scroll.md
            // section 11.3.12).
            ColourToken::ScrollThumb => (alpha(0x000000, 400), alpha(0xFFFFFF, 400)),
            ColourToken::MarkGround => (WHITE, WHITE),
            // The lock screen draws on the wallpaper, not on the card, so its type is white in
            // either scheme and its field a flat white glass (design/20-SURFACES.md section 1.9).
            ColourToken::LockInk => (WHITE, WHITE),
            ColourToken::LockInkSoft => (alpha(0xFFFFFF, 780), alpha(0xFFFFFF, 780)),
            ColourToken::LockGlass => (alpha(0xFFFFFF, 240), alpha(0xFFFFFF, 180)),
            ColourToken::LockGlassStrong => (alpha(0xFFFFFF, 380), alpha(0xFFFFFF, 300)),
            ColourToken::LockVeil => (alpha(0x000000, 120), alpha(0x000000, 280)),
            // Proposed (O-3): black at .25 on light, white at .25 on dark.
            ColourToken::HandleRing => (alpha(0x000000, 250), alpha(0xFFFFFF, 250)),
            // `#fff`/`#FFFFFF` on the avatar's person and account tones in both schemes (O-3).
            ColourToken::OnHue => (WHITE, WHITE),
            ColourToken::Accent
            | ColourToken::AccentInk
            | ColourToken::AccentSoft
            | ColourToken::AccentText
            | ColourToken::AccentTextMaterial
            | ColourToken::Seal
            | ColourToken::AccentRing => {
                let light = accent_of(Accent::Blue, Scheme::Light);
                let dark = accent_of(Accent::Blue, Scheme::Dark);
                (Colour::Solid(light.fill), Colour::Solid(dark.fill))
            }
        }
    }
}

/// A colour token as the stylesheet writes it: the table's value in the scope's scheme.
fn colour_css(token: ColourToken, scope: TokenScope) -> CssValue {
    CssValue::computed(token.value(scope.scheme).css())
}

#[cfg(test)]
mod tests {
    use super::{Colour, ColourToken, Hex};
    use crate::appearance::theme::Scheme;
    use ds_core::colour::fit::oklch_bytes;

    /// `(token, scheme, oklch lightness, chroma, hue)`: what each orb colour names.
    const ORB: &[(ColourToken, Scheme, f64, f64, f64)] = &[
        (ColourToken::OrbBg, Scheme::Light, 0.95, 0.02, 264.695),
        (ColourToken::OrbC1, Scheme::Light, 0.75, 0.15, 350.0),
        (ColourToken::OrbC2, Scheme::Light, 0.80, 0.12, 200.0),
        (ColourToken::OrbC3, Scheme::Light, 0.78, 0.14, 280.0),
        (ColourToken::OrbBg, Scheme::Dark, 0.24, 0.02, 264.695),
        (ColourToken::OrbC1, Scheme::Dark, 0.68, 0.16, 350.0),
        (ColourToken::OrbC2, Scheme::Dark, 0.72, 0.13, 200.0),
        (ColourToken::OrbC3, Scheme::Dark, 0.70, 0.15, 280.0),
    ];

    #[test]
    fn orb_colours_are_the_oklch_values_they_name() {
        for (token, scheme, l, c, h) in ORB {
            let want = Colour::Solid(Hex(oklch_bytes(*l, *c, *h)));
            assert_eq!(token.value(*scheme), want, "{token:?} {scheme:?}");
        }
    }
}
